---
- name: Ensure system is updated to the latest patchlevel
  package:
    state: latest
    name: "*"
  when: check_reboot_update
  register: check_reboot_register_packageinstall

- name: Set restarting command for RHEL 7.x
  set_fact:
    needs_restarting_command: "needs-restarting -r"
  when:
    - ansible_os_family == 'RedHat'
    - ansible_distribution_major_version == '7'

- name: Set restarting command for RHEL 8.1+
  set_fact:
    needs_restarting_command: "yum needs-restarting -r"
  when:
    - ansible_os_family == 'RedHat'
    - ansible_distribution_major_version == '8'
    - ansible_distribution_version != '8.0'

- name: Set restarting command for RHEL 8.0
  set_fact:
    needs_restarting_command: "_IKRNL=$(rpm -q --last kernel | awk 'NR==1{sub(/kernel-/,\"\"); print $1}'); _CKRNL=$(uname -r); if [ ${_IKRNL} != ${_CKRNL} ]; then exit 1; else exit 0; fi"
  when:
    - ansible_os_family == 'RedHat'
    - ansible_distribution_version == '8.0'

- debug:
    var: needs_restarting_command

- name: Check if system needs to be restarted
  shell: "{{ needs_restarting_command }}"
  register: needs_restarting_result
  changed_when: false
  failed_when: false
  args:
    warn: false
  check_mode: false

- debug:
    var: needs_restarting_result

- name: Reboot the server
  reboot:
         reboot_timeout: "{{ check_reboot_timeout }}"
  when: (needs_restarting_result.rc == 1) or (not check_reboot_only_if_needed)
